version: '3.9'
services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - users
      - items
      - wishlist

  users:
    build: ./users
    depends_on:
      - db-users

  items:
    build: ./items
    depends_on:
      - db-items

  wishlist:
    build: ./wishlist
    depends_on:
      - db-wishlist

  db-users:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./users/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-items:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: items
    volumes:
      - ./items/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-wishlist:
    image: mongo
